# Generated by Django 5.1.5 on 2025-02-05 11:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='User Name')),
                ('des', models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff'), ('Faculty', 'Faculty')], max_length=50, verbose_name='User Position')),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.DateField(default=datetime.datetime.today, verbose_name='Borrowing Date')),
                ('rdate', models.DateField(default=datetime.datetime(2025, 2, 20, 17, 1, 37, 923283), verbose_name='Returning Date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.bookdetail', verbose_name='Book Name')),
                ('bwr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERS.userdetail', verbose_name='User')),
            ],
        ),
    ]
