# Generated by Django 5.1.5 on 2025-02-05 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 2, 20, 17, 18, 50, 999581), verbose_name='Returning Date'),
        ),
    ]
