# Generated by Django 5.1.5 on 2025-02-05 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0002_alter_borrower_rdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='due',
            field=models.BooleanField(null=True, verbose_name='Due'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 2, 20, 17, 20, 6, 544831), verbose_name='Returning Date'),
        ),
    ]
