# Generated by Django 5.1.5 on 2025-02-05 11:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0003_borrower_due_alter_borrower_rdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='bwr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 2, 20, 17, 27, 28, 970054), verbose_name='Returning Date'),
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
