# Generated by Django 5.1.5 on 2025-02-05 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0004_alter_borrower_bwr_alter_borrower_rdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 2, 20, 17, 31, 37, 7522), verbose_name='Returning Date'),
        ),
    ]
