# Generated by Django 5.1.5 on 2025-02-06 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0005_alter_borrower_rdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='due',
        ),
        migrations.AddField(
            model_name='borrower',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Due', 'Due')], max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 2, 21, 16, 14, 36, 845546), verbose_name='Returning Date'),
        ),
    ]
