# Generated by Django 5.1.5 on 2025-02-06 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0006_remove_borrower_due_borrower_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 2, 21, 16, 31, 7, 307018), verbose_name='Returning Date'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='status',
            field=models.CharField(choices=[('Not Due', 'Not Due'), ('Returned', 'Returned'), ('Not Returned', 'Not Returned')], max_length=50, null=True, verbose_name='Return Status'),
        ),
    ]
