# Generated by Django 5.1.5 on 2025-02-10 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0007_alter_borrower_rdate_alter_borrower_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 2, 25, 18, 6, 24, 730850), verbose_name='Returning Date'),
        ),
    ]
