# Generated by Django 5.1.5 on 2025-02-11 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0008_alter_borrower_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 10, 20, 49, 113804), verbose_name='Returning Date'),
        ),
    ]
