# Generated by Django 5.1.5 on 2025-02-11 09:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0009_alter_borrower_rdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 14, 56, 18, 166567), verbose_name='Returning Date'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Staff', 'Staff'), ('Faculty', 'Faculty'), ('Student', 'Student')], max_length=10, verbose_name='Role')),
                ('libid', models.CharField(max_length=8, verbose_name='LibraryID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
