# Generated by Django 5.1.5 on 2025-02-11 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0010_alter_borrower_rdate_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 15, 12, 48, 583603), verbose_name='Returning Date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='libid',
            field=models.CharField(max_length=10, verbose_name='LibraryID'),
        ),
    ]
