# Generated by Django 5.1.5 on 2025-02-11 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0012_alter_borrower_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 15, 39, 45, 460356), verbose_name='Returning Date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='libid',
            field=models.CharField(max_length=10, unique=True, verbose_name='LibraryID'),
        ),
    ]
