# Generated by Django 5.1.5 on 2025-02-11 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0013_alter_borrower_rdate_alter_profile_libid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 17, 11, 41, 177906), verbose_name='Returning Date'),
        ),
    ]
