# Generated by Django 5.1.5 on 2025-04-18 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0016_alter_borrower_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 5, 3, 16, 48, 18, 838140), verbose_name='Returning Date'),
        ),
    ]
