# Generated by Django 5.1.5 on 2025-04-18 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0018_alter_borrower_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 5, 3, 17, 47, 7, 402764), verbose_name='Returning Date'),
        ),
    ]
