# Generated by Django 5.1.5 on 2025-04-22 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0019_alter_borrower_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 5, 7, 14, 18, 21, 259872), verbose_name='Returning Date'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='status',
            field=models.CharField(choices=[('Not Due', 'Not Due'), ('Returned', 'Returned'), ('Not Returned', 'Not Returned')], default='Not Returned', max_length=50, null=True, verbose_name='Return Status'),
        ),
    ]
