# Generated by Django 5.1.5 on 2025-04-22 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0021_alter_borrower_rdate_alter_borrower_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 5, 7, 14, 24, 50, 37055), verbose_name='Returning Date'),
        ),
    ]
