# Generated by Django 5.1.5 on 2025-04-22 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0022_alter_borrower_rdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='sub',
            field=models.CharField(default='Null', max_length=50, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='book',
            field=models.CharField(max_length=50, verbose_name='Book Name'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 5, 7, 14, 27, 19, 117299), verbose_name='Returning Date'),
        ),
    ]
