# Generated by Django 5.1.5 on 2025-04-22 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0023_borrower_sub_alter_borrower_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='bwr',
            field=models.CharField(default='-', max_length=50, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 5, 7, 15, 21, 31, 692457), verbose_name='Returning Date'),
        ),
    ]
