# Generated by Django 5.1.5 on 2025-04-22 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0024_alter_borrower_bwr_alter_borrower_rdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='img',
            field=models.ImageField(default='-', upload_to='cover_pages/', verbose_name='Cover Page'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 5, 7, 17, 37, 24, 197345), verbose_name='Returning Date'),
        ),
    ]
