# Generated by Django 5.1.5 on 2025-04-23 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0025_borrower_img_alter_borrower_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 5, 8, 12, 51, 15, 678085), verbose_name='Returning Date'),
        ),
    ]
