# Generated by Django 5.1.5 on 2025-04-23 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0027_alter_borrower_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='rdate',
            field=models.DateField(default=datetime.datetime(2025, 5, 8, 14, 16, 43, 214518), verbose_name='Returning Date'),
        ),
    ]
