# Generated by Django 5.1.5 on 2025-02-04 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name="Author's Name")),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=50, unique=True, verbose_name='Subject Name')),
            ],
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Title of the Book')),
                ('pub', models.CharField(max_length=50, null=True, verbose_name="Publsiher's Name")),
                ('copies', models.PositiveIntegerField(null=True, verbose_name='No. of Copies')),
                ('avail', models.BooleanField(null=True, verbose_name='Availability')),
                ('coverp', models.ImageField(upload_to='cover_pages/', verbose_name='Cover Page')),
                ('author', models.ManyToManyField(to='Books.author')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.subject', verbose_name='Subject Name')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.subject', verbose_name='Subject Name'),
        ),
    ]
