# Generated by Django 5.1.5 on 2025-04-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetail',
            name='copies',
        ),
    ]
