# Generated by Django 5.1.5 on 2025-04-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_remove_bookdetail_copies'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIssueApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookn', models.CharField(max_length=50, verbose_name='Book Name')),
                ('isstime', models.DateField(max_length=50, verbose_name='Date of the Issue')),
                ('issuer', models.CharField(max_length=50, verbose_name='Issuer Name')),
                ('approve', models.CharField(choices=[('Approve', 'Approve'), ('Decline', 'Decline')], default='Not viewed', max_length=50, verbose_name='Approval Status')),
            ],
        ),
    ]
