# Generated by Django 5.1.5 on 2025-04-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_bookissueapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissueapproval',
            name='approve',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Decline', 'Decline'), ('Not viewed', 'Not viewed')], default='Not viewed', max_length=50, verbose_name='Approval Status'),
        ),
    ]
