# Generated by Django 5.1.5 on 2025-04-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_alter_bookissueapproval_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissueapproval',
            name='sub',
            field=models.CharField(default='Null', max_length=50, verbose_name='Subject'),
        ),
    ]
