# Generated by Django 5.1.5 on 2025-04-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_bookissueapproval_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissueapproval',
            name='coverp',
            field=models.ImageField(default='-', upload_to='cover_pages/', verbose_name='Cover Page'),
        ),
    ]
