# Generated by Django 5.1.5 on 2025-04-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_bookissueapproval_coverp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(choices=[('user_borrow_book', 'User Borrow Book'), ('user_return_book', 'User Return Book'), ('user_book_overdue', 'User Book Overdue'), ('new_user_registered', 'New User Registered'), ('new_book_added', 'New Book Added'), ('new_author_registered', 'New Author Registered'), ('new_subject_added', 'New Subject Added')], max_length=50, verbose_name='Category')),
                ('content', models.TextField(verbose_name='Activity')),
            ],
        ),
    ]
