# Generated by Django 5.1.5 on 2025-04-23 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_recentact'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
