# Generated by Django 5.1.5 on 2025-04-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_recentact_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentact',
            name='cat',
            field=models.CharField(choices=[('user_borrow_book', 'User Borrow Book'), ('user_return_book', 'User Return Book'), ('new_user_registered', 'New User Registered'), ('new_book_added', 'New Book Added'), ('new_author_registered', 'New Author Registered'), ('new_subject_added', 'New Subject Added')], max_length=50, verbose_name='Category'),
        ),
    ]
